version: '3'
services:
  app:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    
  db:
    image: postgres:11
    ports:
      - 5432
